### ISSUE TITLE
pip-accel install does not upgrade packages cleanly

### ISSUE THREAD

**Issue by ryanjoneil** [yhat/pip-accel#1]
If you `pip-accel install scikit-learn==0.14.1` and then `pip uninstall scikit-learn`, there will still be an sklearn directory with Python code in it. Upgrading to `scikit-learn==0.15.2` afterward will give a broken build.

```
$ python -c 'from sklearn.metrics.pairwise import manhattan_distances'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 6, in <module>
    from .metrics import (accuracy_score,
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/metrics.py", line 31, in <module>
    from ..preprocessing import LabelBinarizer, label_binarize
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from .data import Binarizer
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py", line 25, in <module>
    from ..utils.sparsefuncs import inplace_column_scale
ImportError: cannot import name inplace_column_scale
```

**Comment by ryanjoneil** [comment]
The issue is that `pip-accel uninstall` does not actually uninstall anything.

```
$ pip-accel install scikit-learn
2015-01-29 16:56:31 kurtag pip_accel[8443] INFO Unpacking source distribution(s) ..
2015-01-29 16:56:31 kurtag pip_accel[8443] INFO Executing command: pip install --no-install --no-index --find-links=file:///home/ryan/.pip-accel/sources --build-directory=/tmp/tmperPOZX scikit-learn
Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking scikit-learn
  Running setup.py egg_info for package scikit-learn
    Partial import of sklearn during the build process.

Successfully downloaded scikit-learn
2015-01-29 16:56:31 kurtag pip_accel[8443] INFO Finished unpacking 1 source distribution in 0.46 seconds.
2015-01-29 16:56:31 kurtag pip_accel[8443] INFO Installing from binary distributions ..
2015-01-29 16:56:32 kurtag pip_accel[8443] INFO Finished installing 1 requirement in 0.56 seconds.

$ ls lib/python2.7/site-packages/scikit_learn-0.14.1-py2.7.egg-info 
lib/python2.7/site-packages/scikit_learn-0.14.1-py2.7.egg-info

$ ls lib/python2.7/site-packages/sklearn/
base.py           cross_decomposition   ensemble            _hmmc.so      _isotonic.so              metrics          neural_network  qda.pyc                tests
base.pyc          cross_validation.py   externals           hmm.py        kernel_approximation.py   mixture          pipeline.py     random_projection.py   test_setup.py
_build_utils.py   cross_validation.pyc  feature_extraction  hmm.pyc       kernel_approximation.pyc  multiclass.py    pipeline.pyc    random_projection.pyc  test_setup.pyc
_build_utils.pyc  datasets              feature_selection   __init__.py   lda.py                    multiclass.pyc   pls.py          semi_supervised        tree
__check_build     decomposition         gaussian_process    __init__.pyc  lda.pyc                   naive_bayes.py   pls.pyc         setup.py               utils
cluster           dummy.py              grid_search.py      isotonic.py   linear_model              naive_bayes.pyc  preprocessing   setup.pyc
covariance        dummy.pyc             grid_search.pyc     isotonic.pyc  manifold                  neighbors        qda.py          svm

$ pip-accel uninstall --yes scikit-learn
Uninstalling scikit-learn:
  Successfully uninstalled scikit-learn

$ ls lib/python2.7/site-packages/scikit_learn-0.14.1-py2.7.egg-info 
ls: cannot access lib/python2.7/site-packages/scikit_learn-0.14.1-py2.7.egg-info: No such file or directory

$ ls lib/python2.7/site-packages/sklearn/
base.py           cross_decomposition   ensemble            _hmmc.so      _isotonic.so              metrics          neural_network  qda.pyc                tests
base.pyc          cross_validation.py   externals           hmm.py        kernel_approximation.py   mixture          pipeline.py     random_projection.py   test_setup.py
_build_utils.py   cross_validation.pyc  feature_extraction  hmm.pyc       kernel_approximation.pyc  multiclass.py    pipeline.pyc    random_projection.pyc  test_setup.pyc
_build_utils.pyc  datasets              feature_selection   __init__.py   lda.py                    multiclass.pyc   pls.py          semi_supervised        tree
__check_build     decomposition         gaussian_process    __init__.pyc  lda.pyc                   naive_bayes.py   pls.pyc         setup.py               utils
cluster           dummy.py              grid_search.py      isotonic.py   linear_model              naive_bayes.pyc  preprocessing   setup.pyc
covariance        dummy.pyc             grid_search.pyc     isotonic.pyc  manifold                  neighbors        qda.py          svm
```

**Comment by ryanjoneil** [comment]
The reason `pip-accel` can't uninstall binary packages is that it is building them using `python setup.py bdist` or `python setup.py bdist_dumb`. These commands do not create an `installed-files.txt`, which is what `pip` uses to track which files belong to a package. The relevent code is [here](https://github.com/yhat/pip-accel/blob/master/pip_accel/bdist.py#L138-L143).

Proposed solution when building a package:
- Create a temporary directory `<TEMP DIR>, and inside it make a structure like`usr/lib/python2.7/site-packages/`.
- Inside the package source run `pip install . --target <TEMP DIR>/usr/lib/python2.7/site-packages/`. This is like doing a dumb binary distribution, but includes the files `pip` uses for package management.
- Tar the contents of `<TEMP DIR>` and continue as before.
