### ISSUE TITLE
issues building lifelines and lifetimes

### ISSUE THREAD

**Issue by ryanjoneil** [yhat/pip-accel#5]
pip-accel for these packages is failing
- `lifetimes==0.1.6.1`
- `lifelines==0.7.0.0`

```
----------------------------------------
  Rolling back uninstall of scipy
Cleaning up...
Command /tmp/tmp.T0M87OK8Ht/bin/python -c "import setuptools;__file__='/tmp/tmp.T0M87OK8Ht/build/scipy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nlP3Yf-record/install-record.txt --single-version-externally-managed --install-headers /tmp/tmp.T0M87OK8Ht/include/site/python2.7 --home=/tmp/tmppga2Eg failed with error code 1 in /tmp/tmp.T0M87OK8Ht/build/scipy
Traceback (most recent call last):
  File "/tmp/tmp.T0M87OK8Ht/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/tmp/tmp.T0M87OK8Ht/local/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/tmp/tmp.T0M87OK8Ht/local/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

**Comment by ryanjoneil** [comment]
Oddly, it works on local ubuntu, but fails in ec2.
